### ISSUE TITLE
Update Competitions Scopes: Breeze

### ISSUE THREAD

**Issue by fer** [Backbase/sites-hackathon#19]
We need to complete this info with:

- URL of the actual server (which will be up 24h during the 18th, 19th and 20th of june): [http://hackathon.backbase.dev:8080/portalserver/home](http://hackathon.backbase.dev:8080/portalserver/home)
- Brief documentation/link about where to find the specs of this API

**Comment by mistermark** [comment]
Should the url be on there right away or will we only expose this on the day of, or the day before, the hackathon?

**Comment by fer** [comment]
It's not a problem if it's there right now.

**Comment by mistermark** [comment]
So where can we find these API spec? And should this information be just added to the list at "Free mode"?
