### ISSUE TITLE
Replace content with winners and their projects

### ISSUE THREAD

**Issue by fer** [Backbase/sites-hackathon#21]
Now that this event has finished, we need to update the site with the following:

- Winners: per category, with special mention to 1st prize.
- Projects: so we'll have a nice set of inspiration projects for next hackathon. These ones should include a small description and maybe an image.
- Video: once it's made, we need to include a link here too.
- Photosets: once the sets of images are gathered, we'll include them in our gallery.

**Comment by mistermark** [comment]
Can we have some quick designs for these as well? Doesn't need to be complex, just pure simplicity.

**Comment by fer** [comment]
@mistermark the designs are on their way :)
