### ISSUE TITLE
Add picture with Prizes section

### ISSUE THREAD

**Issue by mistermark** [Backbase/sites-hackathon#9]

**Comment by fer** [comment]
This section needs to be completed with the actual 'pricing' data:

- 1st: 2500 EUR
- 2nd: 500 EUR
- 3rd ("entertainment" category): concert tickets + dinner/drinks (in Amsterdam)
- 3rd ("creative" category): iPad Air + dinner/drinks  (in Amsterdam)
- 3rd ("murphy law" category): 1 JetBrains License  + dinner/drinks  (in Amsterdam)
